services:
  app:
    build:
      context: .
    container_name: my-gradle-app
    ports:
      - "18080:8080"
    environment:
      - JAVA_OPTS=
    volumes:
      - ./model:/root/Bitus-Labs:ro # 确保模型挂载保留

  nginx:
    image: nginx:alpine
    container_name: my-nginx
    depends_on:
      - app # 仅按顺序启动，不再等 healthy
    ports:
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./certs:/etc/nginx/certs:ro
      - ./model:/root/Bitus-Labs:ro # ← 将主机的 ./model 挂到容器 /root/Bitus-Labs
