name: Sync Docker Hub Overview

on:
  push:
    branches: [main]
    paths: ["README.md"]
  workflow_dispatch:

jobs:
  hub-overview:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install hub-tool
        run: |
          curl -fsSL https://github.com/docker/hub-tool/releases/download/v0.4.9/hub-tool_Linux_x86_64.tar.gz -o hub-tool.tgz
          tar -xzf hub-tool.tgz
          sudo mv hub-tool /usr/local/bin/
          hub-tool version

      - name: Login & set README with hub-tool
        env:
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
        run: |
          hub-tool login -u "$DOCKERHUB_USERNAME" -p "$DOCKERHUB_TOKEN"
          hub-tool repo readme set pudding2718/ml-predict-api --file README.md
